name: digital_assets_analytics
version: "1.0.0"
config-version: 2

profile: digital_assets_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  digital_assets_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: view
